/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
}

group = "de.justplayer"
version = "git"
description = "just-tpa"

val api = "1.21.11"

repositories {
    mavenCentral();
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:$api-R0.1-SNAPSHOT")
}

tasks {
    processResources {
        filteringCharset = Charsets.UTF_8.name()
        val props = mapOf(
            "name" to project.name,
            "version" to project.version,
            "description" to project.description,
            "api" to api
        )
        inputs.properties(props)
        filesMatching("plugin.yml") {
            expand(props)
        }
    }
}